import { FitnessClass } from "@text2rest/shared";

export const CLASSES_STUB: FitnessClass[] = [
  {
    "id": "fc-001",
    "title": "Sunrise Power Yoga",
    "description": "Start your day with energizing flows and deep stretches. Perfect for all levels, this class combines strength and flexibility.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    "classType": "Yoga",
    "duration": 60,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Monday",
    "time": "07:00",
    "date": "2024-01-15",
    "instructor": "Sarah Chen",
    "capacity": 20,
    "booked": 12,
    "available": 8,
    "isAvailable": true,
    "tags": ["Morning", "Popular"]
  },
  {
    "id": "fc-002",
    "title": "HIIT Inferno",
    "description": "High-intensity interval training that will push your limits. Burn calories and build strength in this fast-paced workout.",
    "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    "classType": "HIIT",
    "duration": 45,
    "difficulty": "Advanced",
    "price": 30,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Monday",
    "time": "18:00",
    "date": "2024-01-15",
    "instructor": "Mike Johnson",
    "capacity": 25,
    "booked": 18,
    "available": 7,
    "isAvailable": true,
    "tags": ["Evening", "Hot"]
  },
  {
    "id": "fc-003",
    "title": "Pilates Core Fusion",
    "description": "Strengthen your core and improve posture with controlled movements. Suitable for all fitness levels.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Pilates",
    "duration": 45,
    "difficulty": "Intermediate",
    "price": 28,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Monday",
    "time": "10:00",
    "date": "2024-01-15",
    "instructor": "Emma Williams",
    "capacity": 15,
    "booked": 8,
    "available": 7,
    "isAvailable": true,
    "tags": ["Morning"]
  },
  {
    "id": "fc-004",
    "title": "Spin & Sweat",
    "description": "High-energy cycling class with music and motivation. Get your heart pumping in this intense cardio session.",
    "image": "https://images.unsplash.com/photo-1520877880798-5ee004e3f11e?w=400",
    "classType": "Cycling",
    "duration": 45,
    "difficulty": "Intermediate",
    "price": 32,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Monday",
    "time": "19:30",
    "date": "2024-01-15",
    "instructor": "David Martinez",
    "capacity": 30,
    "booked": 22,
    "available": 8,
    "isAvailable": true,
    "tags": ["Evening", "Popular"]
  },
  {
    "id": "fc-005",
    "title": "Strength & Conditioning",
    "description": "Build muscle and improve functional strength with compound movements and progressive overload techniques.",
    "image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    "classType": "Strength",
    "duration": 60,
    "difficulty": "Intermediate",
    "price": 30,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Tuesday",
    "time": "06:30",
    "date": "2024-01-16",
    "instructor": "James Wilson",
    "capacity": 18,
    "booked": 10,
    "available": 8,
    "isAvailable": true,
    "tags": ["Morning", "New"]
  },
  {
    "id": "fc-006",
    "title": "Yin Yoga Deep Stretch",
    "description": "Slow-paced practice with long-held poses. Perfect for recovery and flexibility. All levels welcome.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Yoga",
    "duration": 75,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Tuesday",
    "time": "17:00",
    "date": "2024-01-16",
    "instructor": "Lisa Anderson",
    "capacity": 20,
    "booked": 14,
    "available": 6,
    "isAvailable": true,
    "tags": ["Evening"]
  },
  {
    "id": "fc-007",
    "title": "Bootcamp Blast",
    "description": "Military-style training combining cardio and strength. Push yourself to new limits in this challenging class.",
    "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    "classType": "HIIT",
    "duration": 60,
    "difficulty": "Advanced",
    "price": 35,
    "studioId": "studio-004",
    "studioName": "Eastside Athletic",
    "studioAddress": "321 Park Boulevard",
    "studioCity": "Springfield",
    "latitude": 40.7280,
    "longitude": -73.9900,
    "dayOfWeek": "Tuesday",
    "time": "12:00",
    "date": "2024-01-16",
    "instructor": "Alex Thompson",
    "capacity": 22,
    "booked": 15,
    "available": 7,
    "isAvailable": true,
    "tags": ["Lunch", "Hot"]
  },
  {
    "id": "fc-008",
    "title": "Barre Basics",
    "description": "Ballet-inspired workout that tones and strengthens. Low-impact but highly effective for all fitness levels.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Barre",
    "duration": 45,
    "difficulty": "Beginner",
    "price": 28,
    "studioId": "studio-004",
    "studioName": "Eastside Athletic",
    "studioAddress": "321 Park Boulevard",
    "studioCity": "Springfield",
    "latitude": 40.7280,
    "longitude": -73.9900,
    "dayOfWeek": "Wednesday",
    "time": "09:00",
    "date": "2024-01-17",
    "instructor": "Sophie Brown",
    "capacity": 16,
    "booked": 9,
    "available": 7,
    "isAvailable": true,
    "tags": ["Morning"]
  },
  {
    "id": "fc-009",
    "title": "Hot Yoga Flow",
    "description": "Vinyasa flow in a heated room. Detoxify and deepen your practice in this challenging yet rewarding class.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    "classType": "Yoga",
    "duration": 60,
    "difficulty": "Intermediate",
    "price": 30,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Wednesday",
    "time": "18:30",
    "date": "2024-01-17",
    "instructor": "Sarah Chen",
    "capacity": 20,
    "booked": 20,
    "available": 0,
    "isAvailable": false,
    "tags": ["Evening", "Hot", "Popular"]
  },
  {
    "id": "fc-010",
    "title": "Cycling Endurance",
    "description": "Long-distance cycling class focusing on endurance and stamina. Perfect for building cardiovascular fitness.",
    "image": "https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=400",
    "classType": "Cycling",
    "duration": 60,
    "difficulty": "Advanced",
    "price": 32,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Wednesday",
    "time": "07:00",
    "date": "2024-01-17",
    "instructor": "David Martinez",
    "capacity": 30,
    "booked": 18,
    "available": 12,
    "isAvailable": true,
    "tags": ["Morning"]
  },
  {
    "id": "fc-011",
    "title": "Quick HIIT Express",
    "description": "Get maximum results in minimal time. This 30-minute high-intensity workout fits perfectly into your busy schedule.",
    "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    "classType": "HIIT",
    "duration": 30,
    "difficulty": "Intermediate",
    "price": 22,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Thursday",
    "time": "12:30",
    "date": "2024-01-18",
    "instructor": "Mike Johnson",
    "capacity": 25,
    "booked": 16,
    "available": 9,
    "isAvailable": true,
    "tags": ["Lunch", "New"]
  },
  {
    "id": "fc-012",
    "title": "Power Pilates",
    "description": "Dynamic Pilates class that challenges your core and builds full-body strength. Expect to work hard!",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Pilates",
    "duration": 50,
    "difficulty": "Advanced",
    "price": 30,
    "studioId": "studio-004",
    "studioName": "Eastside Athletic",
    "studioAddress": "321 Park Boulevard",
    "studioCity": "Springfield",
    "latitude": 40.7280,
    "longitude": -73.9900,
    "dayOfWeek": "Thursday",
    "time": "19:00",
    "date": "2024-01-18",
    "instructor": "Emma Williams",
    "capacity": 15,
    "booked": 11,
    "available": 4,
    "isAvailable": true,
    "tags": ["Evening"]
  },
  {
    "id": "fc-013",
    "title": "Restorative Yoga",
    "description": "Gentle, relaxing practice using props for support. Perfect for stress relief and recovery after intense workouts.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    "classType": "Yoga",
    "duration": 75,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Friday",
    "time": "08:00",
    "date": "2024-01-19",
    "instructor": "Lisa Anderson",
    "capacity": 20,
    "booked": 7,
    "available": 13,
    "isAvailable": true,
    "tags": ["Morning"]
  },
  {
    "id": "fc-014",
    "title": "Friday Night Spin",
    "description": "End your week with an energetic cycling session. Great music, great vibes, and an amazing workout!",
    "image": "https://images.unsplash.com/photo-1554470166-20d3f466089b?w=400",
    "classType": "Cycling",
    "duration": 45,
    "difficulty": "Intermediate",
    "price": 32,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Friday",
    "time": "18:00",
    "date": "2024-01-19",
    "instructor": "Julie Chan",
    "capacity": 30,
    "booked": 25,
    "available": 5,
    "isAvailable": true,
    "tags": ["Evening", "Popular"]
  },
  {
    "id": "fc-015",
    "title": "Weekend Warrior Strength",
    "description": "Intense strength training session perfect for your weekend workout. Build muscle and boost your metabolism.",
    "image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    "classType": "Strength",
    "duration": 90,
    "difficulty": "Advanced",
    "price": 35,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Saturday",
    "time": "10:00",
    "date": "2024-01-20",
    "instructor": "James Wilson",
    "capacity": 18,
    "booked": 12,
    "available": 6,
    "isAvailable": true,
    "tags": ["Morning", "Weekend"]
  },
  {
    "id": "fc-016",
    "title": "Saturday Morning Flow",
    "description": "Start your weekend right with a peaceful yoga flow. Set intentions and move your body mindfully.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    "classType": "Yoga",
    "duration": 60,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-004",
    "studioName": "Eastside Athletic",
    "studioAddress": "321 Park Boulevard",
    "studioCity": "Springfield",
    "latitude": 40.7280,
    "longitude": -73.9900,
    "dayOfWeek": "Saturday",
    "time": "09:00",
    "date": "2024-01-20",
    "instructor": "Sarah Chen",
    "capacity": 20,
    "booked": 15,
    "available": 5,
    "isAvailable": true,
    "tags": ["Morning", "Weekend"]
  },
  {
    "id": "fc-017",
    "title": "Sunday Stretch & Restore",
    "description": "Gentle movement and deep stretching to prepare for the week ahead. Perfect for recovery and relaxation.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Yoga",
    "duration": 60,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Sunday",
    "time": "11:00",
    "date": "2024-01-21",
    "instructor": "Lisa Anderson",
    "capacity": 20,
    "booked": 9,
    "available": 11,
    "isAvailable": true,
    "tags": ["Morning", "Weekend"]
  },
  {
    "id": "fc-018",
    "title": "HIIT Power Hour",
    "description": "Full-body high-intensity workout that combines strength and cardio. Push your limits and see results fast!",
    "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    "classType": "HIIT",
    "duration": 60,
    "difficulty": "Advanced",
    "price": 30,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Sunday",
    "time": "16:00",
    "date": "2024-01-21",
    "instructor": "Alex Thompson",
    "capacity": 25,
    "booked": 13,
    "available": 12,
    "isAvailable": true,
    "tags": ["Afternoon", "Weekend"]
  },
  {
    "id": "fc-019",
    "title": "Sunrise Power Yoga",
    "description": "Start your day with energizing flows and deep stretches. Perfect for all levels, this class combines strength and flexibility.",
    "image": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400",
    "classType": "Yoga",
    "duration": 60,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Monday",
    "time": "07:00",
    "date": "2024-01-22",
    "instructor": "Sarah Chen",
    "capacity": 20,
    "booked": 14,
    "available": 6,
    "isAvailable": true,
    "tags": ["Morning", "Popular"]
  },
  {
    "id": "fc-020",
    "title": "HIIT Inferno",
    "description": "High-intensity interval training that will push your limits. Burn calories and build strength in this fast-paced workout.",
    "image": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400",
    "classType": "HIIT",
    "duration": 45,
    "difficulty": "Advanced",
    "price": 30,
    "studioId": "studio-001",
    "studioName": "Downtown Fitness",
    "studioAddress": "123 Main Street",
    "studioCity": "Springfield",
    "latitude": 40.7128,
    "longitude": -74.0060,
    "dayOfWeek": "Monday",
    "time": "18:00",
    "date": "2024-01-22",
    "instructor": "Mike Johnson",
    "capacity": 25,
    "booked": 20,
    "available": 5,
    "isAvailable": true,
    "tags": ["Evening", "Hot"]
  },
  {
    "id": "fc-021",
    "title": "Pilates Core Fusion",
    "description": "Strengthen your core and improve posture with controlled movements. Suitable for all fitness levels.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Pilates",
    "duration": 45,
    "difficulty": "Intermediate",
    "price": 28,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Monday",
    "time": "10:00",
    "date": "2024-01-22",
    "instructor": "Emma Williams",
    "capacity": 15,
    "booked": 10,
    "available": 5,
    "isAvailable": true,
    "tags": ["Morning"]
  },
  {
    "id": "fc-022",
    "title": "Spin & Sweat",
    "description": "High-energy cycling class with music and motivation. Get your heart pumping in this intense cardio session.",
    "image": "https://images.unsplash.com/photo-1520877880798-5ee004e3f11e?w=400",
    "classType": "Cycling",
    "duration": 45,
    "difficulty": "Intermediate",
    "price": 32,
    "studioId": "studio-002",
    "studioName": "Riverside Studio",
    "studioAddress": "456 River Road",
    "studioCity": "Springfield",
    "latitude": 40.7580,
    "longitude": -74.0015,
    "dayOfWeek": "Monday",
    "time": "19:30",
    "date": "2024-01-22",
    "instructor": "David Martinez",
    "capacity": 30,
    "booked": 24,
    "available": 6,
    "isAvailable": true,
    "tags": ["Evening", "Popular"]
  },
  {
    "id": "fc-023",
    "title": "Strength & Conditioning",
    "description": "Build muscle and improve functional strength with compound movements and progressive overload techniques.",
    "image": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
    "classType": "Strength",
    "duration": 60,
    "difficulty": "Intermediate",
    "price": 30,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Tuesday",
    "time": "06:30",
    "date": "2024-01-23",
    "instructor": "James Wilson",
    "capacity": 18,
    "booked": 11,
    "available": 7,
    "isAvailable": true,
    "tags": ["Morning", "New"]
  },
  {
    "id": "fc-024",
    "title": "Yin Yoga Deep Stretch",
    "description": "Slow-paced practice with long-held poses. Perfect for recovery and flexibility. All levels welcome.",
    "image": "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400",
    "classType": "Yoga",
    "duration": 75,
    "difficulty": "Beginner",
    "price": 25,
    "studioId": "studio-003",
    "studioName": "Westside Gym",
    "studioAddress": "789 Oak Avenue",
    "studioCity": "Springfield",
    "latitude": 40.7505,
    "longitude": -74.0150,
    "dayOfWeek": "Tuesday",
    "time": "17:00",
    "date": "2024-01-23",
    "instructor": "Lisa Anderson",
    "capacity": 20,
    "booked": 16,
    "available": 4,
    "isAvailable": true,
    "tags": ["Evening"]
  }
]